# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, ‘11.0’
use_frameworks!

target 'CryptoATM' do

pod 'Parse'
pod 'Fabric'
pod 'Crashlytics'
pod 'Mapbox-iOS-SDK', '~> 3.6.4'
pod 'Kingfisher', '~> 4.0'
pod 'Firebase/Core'
pod 'Firebase/Crash'
pod 'Firebase/Performance'
pod 'Analytics', '~> 3.0'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

end
